name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check imports (basic test)
      run: |
        python -c "import fastapi, sklearn, xgboost, pandas, numpy"

    - name: Run basic API test
      run: |
        python -c "from app.main import app; print('App loads successfully')"

    - name: Build Docker image
      run: |
        docker build -t credit-risk-app .